### PR TITLE
Added dump and pot

### PR DESCRIPTION
**Pull request by andy8052**
Added the specs for the accessors Vow.dump and End.pot.

I ran the specs and both are passing.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
Do we need to upgrade the `dss` version for these specs?
As otherwise CI will run every spec again.
I'd suggest we upgrade `dss` only if necessary or after we apply all the pending changes.

**Comment by andy8052** [comment]
Didn't even think about that. I can revert that

**Comment by gbalabasquer** [comment]
Actually seems your PR is setting the `dss` commit back to `9b5d1ac` which is the one being used in the CI.

**Comment by kmbarry1** [comment]
Yeah let's not update `dss` in this PR (I think current `k-dss` is already on latest master of `dss` anyway).

Otherwise, LGTM!

**Review by kmbarry1 — APPROVED** [review]

**Pull request merged**
